"""Add conversation file attachments and conversation shares tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-02-26 10:00:00.000000

"""
from __future__ import annotations

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### conversation_file_attachments table ###
    op.create_table(
        'conversation_file_attachments',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('message_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('file_name', sa.String(255), nullable=False),
        sa.Column('file_type', sa.String(50), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('storage_path', sa.String(), nullable=False),
        sa.Column(
            'extracted_content', sa.String(), nullable=True,
            comment='Extracted text content from file processing',
        ),
        sa.Column(
            'processing_status', sa.String(20), nullable=False,
            server_default='pending',
            comment='Processing status: pending, processing, success, failed',
        ),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversations.id'], ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['message_id'], ['messages.id'], ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_conversation_file_attachments_id'),
        'conversation_file_attachments', ['id'], unique=False,
    )
    op.create_index(
        op.f('ix_conversation_file_attachments_user_id'),
        'conversation_file_attachments', ['user_id'], unique=False,
    )
    op.create_index(
        op.f('ix_conversation_file_attachments_conversation_id'),
        'conversation_file_attachments', ['conversation_id'], unique=False,
    )
    op.create_index(
        op.f('ix_conversation_file_attachments_message_id'),
        'conversation_file_attachments', ['message_id'], unique=False,
    )

    # ### conversation_shares table ###
    op.create_table(
        'conversation_shares',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('conversation_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('shared_by_user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('permission', sa.String(20), nullable=False, server_default='view'),
        sa.Column('is_public', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('share_token', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['conversation_id'], ['conversations.id'], ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_conversation_shares_id'),
        'conversation_shares', ['id'], unique=False,
    )
    op.create_index(
        op.f('ix_conversation_shares_conversation_id'),
        'conversation_shares', ['conversation_id'], unique=False,
    )
    op.create_index(
        op.f('ix_conversation_shares_shared_by_user_id'),
        'conversation_shares', ['shared_by_user_id'], unique=False,
    )
    op.create_index(
        op.f('ix_conversation_shares_share_token'),
        'conversation_shares', ['share_token'], unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_shares_share_token'), table_name='conversation_shares')
    op.drop_index(op.f('ix_conversation_shares_shared_by_user_id'), table_name='conversation_shares')
    op.drop_index(op.f('ix_conversation_shares_conversation_id'), table_name='conversation_shares')
    op.drop_index(op.f('ix_conversation_shares_id'), table_name='conversation_shares')
    op.drop_table('conversation_shares')
    op.drop_index(op.f('ix_conversation_file_attachments_message_id'), table_name='conversation_file_attachments')
    op.drop_index(op.f('ix_conversation_file_attachments_conversation_id'), table_name='conversation_file_attachments')
    op.drop_index(op.f('ix_conversation_file_attachments_user_id'), table_name='conversation_file_attachments')
    op.drop_index(op.f('ix_conversation_file_attachments_id'), table_name='conversation_file_attachments')
    op.drop_table('conversation_file_attachments')
    # ### end Alembic commands ###
