// <auto-generated />
using System;
using KnowledgeService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KnowledgeService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KnowledgeDbContext))]
    [Migration("20260529103212_CascadeDeleteDocumentsOnKbDelete")]
    partial class CascadeDeleteDocumentsOnKbDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("ManagingDepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("managing_department_id");

                    b.Property<string>("ManagingDepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("managing_department_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_bases");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_knowledge_bases_code");

                    b.HasIndex("ManagingDepartmentId")
                        .HasDatabaseName("ix_knowledge_bases_managing_department_id");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_knowledge_bases_updated_at");

                    b.ToTable("knowledge_bases", (string)null);
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeBasePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department_name");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_base_permissions");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_knowledge_base_permissions_department_id");

                    b.HasIndex("KnowledgeBaseId")
                        .HasDatabaseName("ix_knowledge_base_permissions_knowledge_base_id");

                    b.ToTable("knowledge_base_permissions", (string)null);
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("current_version");

                    b.Property<decimal>("FileSizeMb")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("file_size_mb");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_type");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<string>("KnowledgeBaseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("knowledge_base_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("VersionCount")
                        .HasColumnType("integer")
                        .HasColumnName("version_count");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_documents");

                    b.HasIndex("KnowledgeBaseId")
                        .HasDatabaseName("ix_knowledge_documents_knowledge_base_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_knowledge_documents_status");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_knowledge_documents_uploaded_at");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeDocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChangeNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("change_note");

                    b.Property<string>("ContentSummary")
                        .HasColumnType("text")
                        .HasColumnName("content_summary");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version_number");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_document_versions");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_knowledge_document_versions_document_id");

                    b.ToTable("knowledge_document_versions", (string)null);
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<decimal>("FileSizeMb")
                        .HasColumnType("decimal(10,4)")
                        .HasColumnName("file_size_mb");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_type");

                    b.Property<Guid>("KnowledgeBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_base_id");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_files");

                    b.HasIndex("FileType")
                        .HasDatabaseName("ix_knowledge_files_file_type");

                    b.HasIndex("KnowledgeBaseId")
                        .HasDatabaseName("ix_knowledge_files_knowledge_base_id");

                    b.HasIndex("SourceDocumentId")
                        .HasDatabaseName("ix_knowledge_files_source_document_id");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("ix_knowledge_files_uploaded_at");

                    b.ToTable("knowledge_files", (string)null);
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeFilePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department_name");

                    b.Property<Guid>("KnowledgeFileId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_file_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_file_permissions");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_knowledge_file_permissions_department_id");

                    b.HasIndex("KnowledgeFileId")
                        .HasDatabaseName("ix_knowledge_file_permissions_knowledge_file_id");

                    b.ToTable("knowledge_file_permissions", (string)null);
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeBasePermission", b =>
                {
                    b.HasOne("KnowledgeService.Domain.Entities.KnowledgeBase", "KnowledgeBase")
                        .WithMany("Permissions")
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_base_permissions_knowledge_bases_knowledge_base_id");

                    b.Navigation("KnowledgeBase");
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("KnowledgeService.Domain.Entities.KnowledgeBase", null)
                        .WithMany()
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_documents_knowledge_bases_knowledge_base_id");
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeDocumentVersion", b =>
                {
                    b.HasOne("KnowledgeService.Domain.Entities.KnowledgeDocument", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_document_versions_knowledge_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeFile", b =>
                {
                    b.HasOne("KnowledgeService.Domain.Entities.KnowledgeBase", "KnowledgeBase")
                        .WithMany("Files")
                        .HasForeignKey("KnowledgeBaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_files_knowledge_bases_knowledge_base_id");

                    b.Navigation("KnowledgeBase");
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeFilePermission", b =>
                {
                    b.HasOne("KnowledgeService.Domain.Entities.KnowledgeFile", "KnowledgeFile")
                        .WithMany("Permissions")
                        .HasForeignKey("KnowledgeFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_file_permissions_knowledge_files_knowledge_file_id");

                    b.Navigation("KnowledgeFile");
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeBase", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeDocument", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("KnowledgeService.Domain.Entities.KnowledgeFile", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
